### ISSUE TITLE
Posibles mejoras en el AdminController

### ISSUE THREAD

**Issue by manuel-freire** [AlexCCo/UCMH#4]
- [x] Cada sesión es independiente (el atributo se sobreescribirá antes de entrar en cada método): https://github.com/AlexCCo/UCMH/blob/master/ucmh/src/main/java/es/fdi/ucm/ucmh/controller/AdminController.java#L60-L62

- [x] No uses synchronized en un controlador: https://github.com/AlexCCo/UCMH/blob/master/ucmh/src/main/java/es/fdi/ucm/ucmh/controller/AdminController.java#L95

- [x] Es innecesario (aunque tampoco resulta peligroso) dejar `@Secured` en algo cuyo acceso ya está restringido a nivel de `SecurityConfig`: https://github.com/AlexCCo/UCMH/blob/master/ucmh/src/main/java/es/fdi/ucm/ucmh/controller/AdminController.java#L115

- [x] Esto debería ser un `if`, porque es independiente del `if` anterior, y por tanto `else if` no tiene sentido: https://github.com/AlexCCo/UCMH/blob/master/ucmh/src/main/java/es/fdi/ucm/ucmh/controller/AdminController.java#L214

- [x] Poder eliminar admines debería estar permitido. Es bueno no permitir eliminar el último admin, pero en general, si puedes añadir algo, debes poder también eliminarlo: https://github.com/AlexCCo/UCMH/blob/master/ucmh/src/main/java/es/fdi/ucm/ucmh/controller/AdminController.java#L255

- [x] No dejes código muerto en un archivo bajo control de versiones. Si quieres ver cómo estaba antes, míralo en las versiones, no en un comentario: https://github.com/AlexCCo/UCMH/blob/master/ucmh/src/main/java/es/fdi/ucm/ucmh/controller/AdminController.java#L255

- [x] Los paquetes en java tienen nombres en minúsculas. Evita paquetes con 1 único fichero. `controller.Auxiliary`, te estoy mirando.

- [x] Hay mucho código duplicado en 
https://github.com/AlexCCo/UCMH/blob/master/ucmh/src/main/java/es/fdi/ucm/ucmh/controller/Auxiliary/PageCache.java ; por ejemplo, la diferencia entre getListPATLess y getListPSYLess son 2 caracteres (`PSY` -> `PAT`). PageCache debería servir para cualquier lista de resultados paginable (lo interesante es el juego entre el minId y el maxId, el resto de la consulta preparada debería venir por parámetro), no tiene sentido que sea específica para listas de PSYs y PATs. Cuestiono también su utilidad, ya que quiere decir que los resultados que se muestran pueden, potencialmente, estar muy desactualizados (si una sesión dura 2 horas, y en ese tiempo cambian cosas en la BD, la PageCache no se refrescará - ni tiene ninguna forma de hacerlo). Deberías, ya puestos, tener una PageCache para PSYs y otra para PATs; y de esa forma, cada PageCache tendría 1 idMin, 1 idMax, y 1 lista. Y un método getMore y otro getLess. Y recibiría como parámetro la parte entidad-específica de la consulta.

- [x] El repositorio git contiene mucha basura. Sobra todo /ucmh/bin (que además ocupa más que todo lo demás junto).

**Comment by AlexCCo** [comment]
Con lo del PageCache, siguiento el consejo de que haya uno para PSYs y otro para PATs, he decidido hacer una clase abstracta denominada PageCache que los métodos abstracto getMore y getLess para solucionar el problema.

Para lo de los resultados desactualizados no hay ningún problema en principio, tal y como están pensadas las queries, siempre se obtendrá los valores más recientes de la base de datos, no sé si doy a entender mi punto aquí. Es decir, se estás en una sesión de 2 horas y no le has dado a las flechas que provocan las queries que usa PageCache, obviamente se podrán ver datos desactualizados, aunque eso creo que es cosa de todas las páginas webs que puedan existir, en el caso de que le des a las flechas, siempre se verán los resultados más recientes de la base de datos y por ello el uso de una única variable "lastUserId" y de una única lista "lastListUser"

**Comment by AlexCCo** [comment]
El único caso en el que podría generar algún tipo de vista desactualizada que pueda ser extraño es el caso en el que se se añada o actualice un usuario que está en la lista que se está visualizando actualemente en la template del admin, ahí no hay solución alguna, o al menos no hay ninguna que se me haya ocurrido que sea eficiente. Yo clasificaría eso como un error en mi diseño, aunque puede resultar poco probable que ocurra esta situación, no lo sé a ciencia cierta
